[theme]
primaryColor = "#2b6cb0"
backgroundColor = "#f5f7f9"
secondaryBackgroundColor = "#e6f7ff"
textColor = "#262730"
font = "sans serif"

[server]
enableCORS = false
enableXsrfProtection = false
headless = true

[browser]
gatherUsageStats = false
