name: Sync to Hugging Face Space

on:
  push:
    branches: [main]

  # to run this workflow manually from the Actions tab 
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: false
      
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "abdussamadidrisali@gmail.com"
          git config --global user.name "AbdussamadAI"
          git remote set-url origin https://AbdussamadAI:$HF_TOKEN@huggingface.co/spaces/AbdussamadAI/university-portal-assistant
          git push --force origin main
